# Кнопка «Sponsor» на GitHub. Добровольная поддержка проекта.
# Формат: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://finance.ozon.ru/apps/sbp/ozonbankpay/019eb07a-89a8-7a66-8554-25fa17b124c7"]
